spring:
  data:
    mongodb:
      uri: mongodb://mongo/${MONGO_DBNAME}
    jpa:
      database: MYSQL
      hibernate:
        ddl-auto: create-drop
    datasource:
      url: jdbc:mysql://mysql:3306/ghost
      username: ghost
      password: password
      driver-class-name: com.mysql.jdbc.Driver